import type { Metadata } from "next";
import { Inter, Cabin } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import Layout from "@/components/layout/layout";

const cabin = Cabin({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cabin.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
